### PR TITLE
Update test data from Generator 1.1.0 to 1.2.0. Includes all regressions...

### PR DESCRIPTION
**Pull request by dirkschulze**
....

### CODE REVIEW

**Comment by dirkschulze** [comment]
I updated all files regardless if the test fails or not. We should track all failures in separate bug reports.

**Comment by dirkschulze** [comment]
Ok, it is probably not as bad as the diff makes it look like. I looked over all failing tests.

1) We actually have 1-2 progressions.
2) Most of the failing tests actually don't fail but the original PSD file looked different in the past. The tests are now updated to reflect the existing test files.
3) 3 tests are broken because the rectangles were replaced by paths. With Dmitry's fix for issue #136 this should be solved.
4) text-on-path is the only actually failing test and it fails badly. This is because the Generator JSON format changed. The value numbers were replaced by value objects with the actual number and a unit. Should be an easy fix. Sadly we shipped with the broken behavior.

**Comment by jhatwich** [comment]
Unfortunately we just didn't get to fix text on a path, it was known to be busted.  Glad you figured it out!

**Comment by jhatwich** [comment]
In the future I think we should probably lean on it.skip instead of recording borked media, but for now we know the 2 issues and have fixes for them that are going to land shortly... so I'm going to merge this expecting #136 and #137 to be fixed after which we can lean on the tests again.

**Pull request merged**
